# Generated by Django 5.2.7 on 2025-11-01 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_comment_share_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_likes', to='complaints.complaint'),
        ),
    ]
