# Generated by Django 5.2.7 on 2026-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_like_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='fake_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='text_score',
            field=models.FloatField(default=0),
        ),
    ]
